import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/common/NavBar'
import HomeVideo from '../components/home/HomeVideo'
import Greetings from '../components/home/Greetings'
import Biography from '../components/home/Biography'
import Music from '../components/home/Music'
import Calendar from '../components/home/Calendar'
import Multimedia from '../components/home/Multimedia'
import Contact from '../components/home/Contact'
import Store from '../components/home/Store'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>NIÑA LOBO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <div className="container">

        <main>
          <Greetings />
          <Biography />
          <Music />
          <Calendar />
          <Multimedia />
          <Store />
          <Contact />

        </main>

        {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      </div>
    </>
  )
}

export default Home
